- .travis.yml
- ci/before_script.sh
- ci/script.sh
- package.json
This PR work with:
- add package information
- improve travis scripts
> Fixes of deploy with Travis CI

- app/src/main/java/org/flyve/inventory/agent/Accueil.java
- app/src/main/java/org/flyve/inventory/agent/BootStartAgent.java
- app/src/main/java/org/flyve/inventory/agent/InventoryAgentApp.java
- app/src/main/java/org/flyve/inventory/agent/InventoryService.java
- app/src/main/java/org/flyve/inventory/agent/SplashActivity.java
- app/src/main/java/org/flyve/inventory/agent/TimeAlarm.java
- app/src/main/java/org/flyve/inventory/agent/utils/EasySSLSocketFactory.java
- app/src/main/java/org/flyve/inventory/agent/utils/FlyveLog.java
- app/src/main/java/org/flyve/inventory/agent/utils/HttpInventory.java
Hi, @rafaelje 
This Pull Request adds the code documentation on the java sources
> Code Documentation

- .circleci/README.md
- .circleci/config.yml
- .gitignore
- .tx/README.md
- ci/README.md
- fastlane/README.md
Add information related to continuous integration:
- .circleci  
- .tx 
- ci 
- fastlane
> Add readme to understand continuous integration files and configuration

- app/build.gradle
- app/src/main/java/org/flyve/inventory/agent/Accueil.java
- app/src/main/java/org/flyve/inventory/agent/InventoryAgentApp.java
- app/src/main/java/org/flyve/inventory/agent/TimeAlarm.java
- app/src/main/java/org/flyve/inventory/agent/utils/HttpInventory.java
- app/src/main/res/xml/accueil.xml
- ACRA basic implementation
- Server default value
- Tested and solved unknown error when clicking on Run Inventory 
close: https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent/issues/38
> Add ACRA support

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/flyve/inventory/agent/InventoryAgentApp.java
This PR implement bugsnag with bugsnag.com
close: https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent/issues/43
> Implement bugsnag

- .circleci/config.yml
- .gitignore
- app/build.gradle
- app/src/androidTest/java/org/flyve/inventory/agent/MainActivityTest.java
- app/src/androidTest/java/org/flyve/inventory/agent/SplashTest.java
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/flyve/inventory/agent/InventoryAgentApp.java
- fastlane/Screengrabfile
This PR works with: 
Take Screenshot with UI Test and store like artifact on CircleCI
> Take screenshot with UI Test

- app/build.gradle
- app/src/main/java/org/flyve/inventory/agent/AboutActivity.java
- ci/scripts/ci_about.sh
Fix AndroidManifest path required on update version and code
> Fix AndroidManifest path

- app/src/main/java/org/flyve/inventory/agent/FragmentAccueil.java
- app/src/main/java/org/flyve/inventory/agent/InventoryAgentApp.java
- app/src/main/java/org/flyve/inventory/agent/SplashActivity.java
- app/src/main/java/org/flyve/inventory/agent/utils/ConnectionHTTP.java
- app/src/main/java/org/flyve/inventory/agent/utils/HttpInventory.java
- app/src/main/java/org/flyve/inventory/agent/utils/LocalStorage.java
- app/src/main/java/org/flyve/inventory/agent/utils/UtilsCrash.java
- app/src/main/res/xml/accueil.xml
Add privacy functionality:
close: https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent/issues/48
> Add privacy functionality

- app/build.gradle
- app/src/main/java/org/flyve/inventory/agent/FragmentAccueil.java
- app/src/main/java/org/flyve/inventory/agent/MainActivity.java
- app/src/main/java/org/flyve/inventory/agent/utils/Helpers.java
- app/src/main/java/org/flyve/inventory/agent/utils/HttpInventory.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/accueil.xml
- Add new item on main screen about and remove the right menu
- Improve labels descriptions
- Improve error messages
- Improve anonymous data sent
- Add new inventory library version
> Improve Inventory Agent

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/flyve/inventory/agent/AboutActivity.java
- app/src/main/java/org/flyve/inventory/agent/FragmentAccueil.java
- app/src/main/java/org/flyve/inventory/agent/InventoryActivity.java
- app/src/main/java/org/flyve/inventory/agent/InventoryAgentApp.java
- app/src/main/java/org/flyve/inventory/agent/adapter/InventoryAdapter.java
- app/src/main/java/org/flyve/inventory/agent/utils/HttpInventory.java
- app/src/main/res/drawable/separator_line.xml
- app/src/main/res/layout/activity_inventory.xml
- app/src/main/res/layout/list_item_inventory.xml
- app/src/main/res/layout/list_item_inventory_header.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/xml/accueil.xml
- ci/scripts/ci_about.sh
Add **Show my inventory feature**
- Solved commit link in the about page return status 404
close: https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent/issues/63
- Solved Inventory back-end reply
close: https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent/issues/59
> Fix issues and add My Inventory 

- app/src/main/java/org/flyve/inventory/agent/utils/HttpInventory.java
This PR fix the URL to send the inventory on instrumented test
> Fix inventory task issue on instrumented test

- app/src/androidTest/java/org/flyve/inventory/agent/InventoryTest.java
- app/src/main/java/org/flyve/inventory/agent/InventoryActivity.java
- app/src/main/java/org/flyve/inventory/agent/InventoryAgentApp.java
- app/src/main/java/org/flyve/inventory/agent/utils/HttpInventory.java
- app/src/main/res/layout/activity_inventory.xml
- ci/scripts/ci_about.sh
- Fix inventory send to preset url
- Fix about commit
- Add progress bar on inventory show
> Fix issues

- app/src/main/java/org/flyve/inventory/agent/InventoryActivity.java
- app/src/main/java/org/flyve/inventory/agent/adapter/InventoryAdapter.java
- app/src/main/java/org/flyve/inventory/agent/utils/Helpers.java
- app/src/main/res/layout/activity_inventory.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/list_item_inventory.xml
- app/src/main/res/layout/list_item_inventory_header.xml
- app/src/main/res/values/colors.xml
This PR works with the look and feel on inventory list
> Keep the same look and feel

- app/build.gradle
- app/src/main/res/layout/activity_about.xml
- Update new library version
- Improve look and feel on About screen
> Feature update library version

- .circleci/config.yml
- ci/scripts/ci_push_changes.sh
This PR works with
- Rename test name to show on CircleCI website
- Remove filters and configure CircleCI to just run on PR
> Improve CI

- app/src/main/java/org/flyve/inventory/agent/AboutActivity.java
- app/src/main/java/org/flyve/inventory/agent/InventoryActivity.java
- app/src/main/java/org/flyve/inventory/agent/MainActivity.java
- Manage toolbar NullPointerException
close: https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent/issues/78
> Fix toolbar problem

- .circleci/config.yml
- app/build.gradle
- app/src/androidTest/java/org/flyve/inventory/agent/InventoryTest.java
- app/src/main/java/org/flyve/inventory/agent/IdlingResource/RecycleViewIdlingResource.java
- app/src/main/java/org/flyve/inventory/agent/InventoryActivity.java
- ci/scripts/ci_push_screenshot.sh
- ci/scripts/ci_setup.sh
- ci/scripts/ci_updateversion.sh
- Accept new android licenses
- Add build information for screenshot
> Fix screenshot information

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/badge.yml
- .github/settings.yml
Hi, @ajsb85 / @rafaelje 
This PR adds the .github folder containing both the issue and pull request templates, also the yaml file for bot settings
> Adds github folder with templates and settings

- app/src/main/java/org/flyve/inventory/agent/FragmentAccueil.java
- app/src/main/java/org/flyve/inventory/agent/InventoryActivity.java
- app/src/main/java/org/flyve/inventory/agent/utils/ConnectionHTTP.java
- app/src/main/java/org/flyve/inventory/agent/utils/Helpers.java
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```
URIError: URI malformed - Anonymous Report
Close: https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent/issues/86
Fix Version Client
Reference: https://github.com/flyve-mdm/flyve-mdm-android-inventory/issues/73
Now is sending the request with application/json format
```
[ ] Yes
[x] No
```
> Add Application/json on request property

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/invite-contributors.yml
- CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```
- Wrong usage to add team name in invite-contributors file
- Wrong links in contributing and pull request template
- Correct usage to add team name
- Fixed links
- Minor style changes
```
[ ] Yes
[x] No
```
> Update project documentation

- ci/scripts/ci_updateversion.sh
Don't deploy on store the version code is lowest than expected
Update the number factor to increment the build number
> Update version code factor update

- app/build.gradle
Issue # N/A
Update inventory library
> Update inventory library

- app/build.gradle
- app/src/main/java/org/flyve/inventory/agent/InventoryAgentApp.java
- build.gradle
Issue # N/A
Prevent ClassNotFoundException on start by greater than 64K
> Add multidex dependecie

- app/build.gradle
Issue # N/A
Remove external dependencies required by F-Droid
> Remove external dependecies

- .circleci/config.yml
- CHANGELOG.md
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/flyve/inventory/agent/BootStartAgent.java
- app/src/main/java/org/flyve/inventory/agent/FragmentAccueil.java
- app/src/main/java/org/flyve/inventory/agent/InventoryActivity.java
- app/src/main/java/org/flyve/inventory/agent/InventoryAgentApp.java
- app/src/main/java/org/flyve/inventory/agent/InventoryService.java
- app/src/main/java/org/flyve/inventory/agent/MainActivity.java
- app/src/main/java/org/flyve/inventory/agent/TimeAlarm.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Close # 
- Automatic Inventory does not works
close: https://github.com/flyve-mdm/android-inventory-agent/issues/111
- Responsive layout for small screen
ref: https://github.com/flyve-mdm/android-inventory-agent/issues/119
Now the alarm is working correctly
> Fix schedule inventory

- README.md
The license badge link is broken, it directs to a 404
The IRC link adds an square bracket at the end of #flyve-mdm
Close # N/A
Fix links
> Change links of License badge and IRC chat

- fastlane/Fastfile
Close # N/A
Update signer and zipalign on fastlane
> Update signer and zipalign

- .circleci/config.yml
- fastlane/Fastfile
Close # N/A
This project works with Gradle 3.0.1 needs to add release to the path
> Fix CircleCI

- fastlane/Fastfile
- fastlane/Screengrabfile
The zipalign is not working
Close # N/A
Update the path of the aligned apk
> Fix deploy problems

- app/build.gradle
- app/src/main/java/org/flyve/inventory/agent/FragmentAccueil.java
- app/src/main/java/org/flyve/inventory/agent/InventoryAgentApp.java
- app/src/main/java/org/flyve/inventory/agent/TimeAlarm.java
- app/src/main/java/org/flyve/inventory/agent/utils/FlyveLog.java
Fix automatic inventory and interval schedule, added logger and inventory library 0.6.2
Problems with interval schedule and automatic inventory
Close issues:
close: https://github.com/flyve-mdm/android-inventory-agent/issues/129
close: https://github.com/flyve-mdm/android-inventory-agent/issues/132
close: https://github.com/flyve-mdm/android-inventory-agent/issues/133
- Is possible to disable the automatic inventory 
- add new format for interval schedule, the older ways does not work and send notifications any time
- Added and implemented the logger component to create better logs with a format and redirect to the fail log
- Added the inventory library version 0.6.2 on this agent with …
> Fix automatic inventory and interval schedule

- 404.html
- _posts/static/2017-10-09-contributing.md
- _posts/static/2017-11-21-how-to-translate.md
- _posts/static/2017-12-21-installation.md
* How to contribute
Remove guilines
add assistance links
Redirect to the contributing guidelines of the repo
Closes #N/A
> Change contributing articles

- CONTRIBUTING.md
Change old format for the new one, add tests instructions, add feature specification to naming branch examples
Closes #N/A
> Update contributing guidelines to new format

- app/build.gradle
- app/src/main/java/org/flyve/inventory/agent/core/main/Main.java
- app/src/main/java/org/flyve/inventory/agent/core/main/MainModel.java
- app/src/main/java/org/flyve/inventory/agent/core/main/MainPresenter.java
- app/src/main/java/org/flyve/inventory/agent/service/InventoryService.java
- app/src/main/java/org/flyve/inventory/agent/ui/ActivityMain.java
- app/src/main/java/org/flyve/inventory/agent/utils/HttpInventory.java
- app/src/main/java/org/flyve/inventory/agent/utils/LocalStorage.java
- Fix a problem with empty URL now if the URL is empty cancel the action
- Add a Countdown in the toolbar main to show when will be the next inventory on the device, this countdown was reviewed and don't have memory leaks or battery leak
- Update the inventory library to 0.7.0
Closes # N/A
> Empty URL and add countdown for the next inventory

- app/build.gradle
- app/src/main/java/org/flyve/inventory/agent/utils/Helpers.java
- Upgrade all libraries
- Implement changes on old methods 
Closes #N/A
> Upgrade libraries

- .tx/config
Add these languages:
- Arabic (Egypt) (ar_EG)
- Czech (Czech Republic) (cs_CZ) 
- Hebrew (Israel) (he_IL) 
- Arabic (Saudi Arabia) (ar_SA)
Closes #N/A
> Feature add new language from transifex

- _data/whitelist_GP.yml
- _posts/static/2017-11-20-how-to-use.md
- _posts/static/2017-11-21-how-to-translate.md
- _posts/static/2017-11-22-contribute.md
- _posts/static/2018-04-06-workflow.md
- index.html
Change workflow and contributing articles
Improve general redaction
Fix index in how to use article
Add proper link in how to translate
Closes #N/A
> Improve worflow and contributing articles

- .circleci/config.yml
- .github/settings.yml
- .gitignore
- ci/README.md
- ci/scripts/ci_about.sh
- ci/scripts/ci_changelog.sh
- ci/scripts/ci_coverage.sh
- ci/scripts/ci_fastlane.sh
- ci/scripts/ci_git_push.sh
- ci/scripts/ci_github_release.sh
- ci/scripts/ci_javadoc.sh
- ci/scripts/ci_push_changes.sh
- ci/scripts/ci_push_screenshot.sh
- ci/scripts/ci_setup.sh
- ci/scripts/ci_transifex.sh
- ci/scripts/ci_updateversion.sh
- ci/scripts/ci_validate_workflow.sh
- package.json
Change the workflow to update the changelog when there is a merge in master branch
Rename folders in development section for normalization
Remove the header generation in Changelog
Closes #118 
Depends on #159
> Normalize development section

- app/src/main/java/org/flyve/inventory/agent/ui/ActivityMain.java
- Check if the autoinventory sharepreference to show or hide the countdown
Closes #N/A
> Hide and Show the countdown on toolbar

- app/build.gradle
- Add the new inventory library 0.8.5 this library fix get more accurate MAC Address
Closes #N/A
> Update inventory library to 0.8.5

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/flyve/inventory/agent/core/main/Main.java
- app/src/main/java/org/flyve/inventory/agent/core/main/MainModel.java
- app/src/main/java/org/flyve/inventory/agent/core/main/MainPresenter.java
- app/src/main/java/org/flyve/inventory/agent/core/permission/Permission.java
- app/src/main/java/org/flyve/inventory/agent/core/permission/PermissionModel.java
- app/src/main/java/org/flyve/inventory/agent/core/permission/PermissionPresenter.java
- app/src/main/java/org/flyve/inventory/agent/ui/ActivityMain.java
- app/src/main/java/org/flyve/inventory/agent/ui/ActivitySplash.java
- app/src/main/java/org/flyve/inventory/agent/ui/PermissionActivity.java
- app/src/main/res/layout/activity_permission.xml
- app/src/main/res/values/strings.xml
- To prevent the problem with permission on main screen with the splash, create a new descriptive screen with permission information
|:---|:---:|
|@rafaelje |4|
Closes #N/A
Related #N/A
> Fix windows behaviors

- app/src/main/java/org/flyve/inventory/agent/core/splash/SplashModel.java
- app/src/main/java/org/flyve/inventory/agent/utils/Helpers.java
- ci/scripts/ci_github_release.sh
- ci/scripts/ci_push_changes.sh
- Fix one problem with the apk the github release
- Improve the develop merge with the deploy information
- Move the validation from splash model to helper
|:---|:---:|
|@rafaelje|6|
Closes #N/A
Related #N/A
> Fix release deployment on master branch

- ci/scripts/ci_github_release.sh
- Fix github token variable
|:---|:---:|
|@rafaelje |1|
Closes #N/A
Related #N/A
> Fix github token variable

- _posts/static/2017-10-05-how-it-works.md
- _posts/static/2017-11-20-how-to-use.md
- _posts/static/2018-01-04-use-cases.md
Update documentation images
|:---|:---:|
|@Naylin15|2|
Closes #N/A
Related #N/A
> Update screenshots in articles

- .circleci/config.yml
Add filter to run on feature branches too
|:---|:---:|
|@Naylin15|1|
Closes #N/A
Related #N/A
> Add run on feature branches

- app/src/main/AndroidManifest.xml
- Update version code number with the lasted version on production
|:---|:---:|
|@rafaelje|2|
Closes #N/A
Related #N/A
> Update version code

- .circleci/config.yml
- implement updateVersionCode on develop branch
- implement updateVersionCode and updateVersionName on master
|:---|:---:|
|@rafaelje|2|
Closes #N/A
Related #N/A
> Update version code and name on CircleCI yml

- .circleci/config.yml
- .tx/config
- ci/scripts/setup_environment.sh
- ci/scripts/transifex.sh
- Review the language on CI
- Add catalan language
|:---|:---:|
|@rafaelje|4|
Closes #N/A
Related #N/A
> Check languages on CI and Add catalan language

- _posts/static/2017-11-22-contribute.md
add command to import public key
add guide to add email
|:---|:---:|
|@Naylin15|1|
Closes #N/A
Related #N/A
> Add GPG steps

- README.md
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Move contribute block

- app/src/main/java/org/flyve/inventory/agent/ui/InventoryAgentApp.java
- app/src/main/java/org/flyve/inventory/agent/utils/CustomSSLSocketFactory.java
- app/src/main/java/org/flyve/inventory/agent/utils/CustomX509TrustManager.java
- app/src/main/java/org/flyve/inventory/agent/utils/DataLoader.java
- app/src/main/java/org/flyve/inventory/agent/utils/HttpInventory.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/global_parameters.xml
Improved https connection
|:---|:---:|
|@ivans51|10|
Closes: https://github.com/flyve-mdm/android-inventory-agent/issues/200
Related #N/A
> Send inventory to GLPI successfully

- app/build.gradle
- app/src/main/assets/inventory.xml
- app/src/main/java/org/flyve/inventory/agent/broadcast/TimeAlarm.java
- app/src/main/java/org/flyve/inventory/agent/service/InventoryService.java
- app/src/main/java/org/flyve/inventory/agent/ui/DialogListServers.java
- app/src/main/res/layout/dialog_list_servers.xml
- app/src/main/res/values/strings.xml
- ci/scripts/setup_environment.sh
Validated empty list server
Changed version in the gradle on inventory library
|:---|:---:|
|@ivans51|6|
Closes: https://github.com/flyve-mdm/android-inventory-agent/issues/204
Related #N/A
> Show message when list servers is empty

- app/src/main/java/org/flyve/inventory/agent/ui/DialogListServers.java
Now is possible to send inventory to all servers register by the user
|:---|:---:|
|@ivans51|2|
Closes: https://github.com/flyve-mdm/android-inventory-agent/issues/209
Related #N/A
> Send inventory to all servers

- app/src/main/AndroidManifest.xml
Changed version code in manifest
|:---|:---:|
|@ivans51|1|
Closes: https://github.com/flyve-mdm/android-inventory-agent/issues/211
Related #N/A
> Changed version code in manifest

- app/build.gradle
- app/src/androidTest/java/org/flyve/inventory/agent/InventoryTaskTest.java
- app/src/main/java/org/flyve/inventory/agent/broadcast/TimeAlarm.java
- app/src/main/java/org/flyve/inventory/agent/service/InventoryService.java
- app/src/main/java/org/flyve/inventory/agent/ui/DialogListServers.java
Upgrade version about inventory library
|:---|:---:|
|@ivans51|2|
Closes #N/A
Related #N/A
> Upgrade inventory library

- .circleci/config.yml
- ci/scripts/deploy_alpha.sh
- ci/scripts/deploy_production.sh
- ci/scripts/release.sh
Config to CI
Config to deploy beta channel
Config to deploy production channel
|:---|:---:|
|@ivans51|4|
Closes: https://github.com/flyve-mdm/android-inventory-agent/issues/215
Related #N/A
> CI with alpha, beta and production channel in Google Play

- app/src/main/AndroidManifest.xml
Updated version code in manifest
|:---|:---:|
|@ivans51|1|
Closes #N/A
Related #N/A
> Increment the version code to 39164

- app/src/main/AndroidManifest.xml
Add android:largeHeap="true" in manifest
|:---|:---:|
|@ivans51|5|
Closes: https://github.com/flyve-mdm/android-inventory-agent/issues/226
Related #N/A
> Out Memory

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/flyve/inventory/agent/adapter/CategoriesAdapter.java
- app/src/main/java/org/flyve/inventory/agent/broadcast/TimeAlarm.java
- app/src/main/java/org/flyve/inventory/agent/core/categories/Categories.java
- app/src/main/java/org/flyve/inventory/agent/core/categories/CategoriesModel.java
- app/src/main/java/org/flyve/inventory/agent/core/categories/CategoriesPresenter.java
- app/src/main/java/org/flyve/inventory/agent/core/detailserver/DetailServerModel.java
- app/src/main/java/org/flyve/inventory/agent/core/report/ReportModel.java
- app/src/main/java/org/flyve/inventory/agent/core/servers/ServersModel.java
- app/src/main/java/org/flyve/inventory/agent/service/InventoryService.java
- app/src/main/java/org/flyve/inventory/agent/ui/ActivityCategories.java
- app/src/main/java/org/flyve/inventory/agent/ui/ActivityMain.java
- app/src/main/java/org/flyve/inventory/agent/ui/DialogListServers.java
- app/src/main/java/org/flyve/inventory/agent/utils/LocalPreferences.java
- app/src/main/java/org/flyve/inventory/agent/utils/Utils.java
- app/src/main/res/layout/activity_list_categories.xml
- app/src/main/res/layout/list_item_categories.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/global_parameters.xml
Added view and button to show lists of categories
Filter to categories in report view
|:---|:---:|
|@ivans51|12|
Closes: https://github.com/flyve-mdm/android-inventory-agent/issues/212
Related #N/A
> Select by categories to show in the inventory

- .tx/config
- app/src/main/AndroidManifest.xml
Add language basque
|:---|:---:|
|@ivans51|1|
Closes #N/A
Related #N/A
> Add language basque in Transifex

- _config.yml
- _posts/static/2017-11-22-contribute.md
- _posts/static/2017-12-21-installation.md
- _posts/static/2018-04-06-workflow.md
- _posts/static/2018-07-24-adb-use.md
General update
add compatibility matrix
|:---|:---:|
|@Naylin15|4|
Closes #N/A 
Related #206
> Review of the project

- README.md
Specify Android compatibility
|:---|:---:|
|@Naylin15|2|
Closes #N/A
Related #237 
> Add compatibility with Android

- app/src/main/res/layout/list_item_inventory_child.xml
Enable copy text in the screen shown inventory
|:---|:---:|
|@ivans51|2|
Closes: https://github.com/flyve-mdm/android-inventory-agent/issues/231
Related #N/A
> Copy Text in screen Show Inventory

- ci/scripts/create_documentation.sh
- ci/scripts/generate_documentation.sh
Add path for code documentation
|:---|:---:|
|@Naylin15|2|
Closes #N/A
Related #N/A
Depends on #240
> Fix path for code documentation

- app/src/main/java/org/flyve/inventory/agent/adapter/CategoriesAdapter.java
- app/src/main/java/org/flyve/inventory/agent/adapter/ViewPagerAdapter.java
- app/src/main/java/org/flyve/inventory/agent/core/categories/CategoriesModel.java
- app/src/main/java/org/flyve/inventory/agent/core/report/ReportModel.java
- app/src/main/java/org/flyve/inventory/agent/ui/ActivityCategories.java
- app/src/main/java/org/flyve/inventory/agent/ui/ActivityInventoryReport.java
- app/src/main/java/org/flyve/inventory/agent/ui/ActivityMain.java
- app/src/main/java/org/flyve/inventory/agent/utils/Utils.java
- app/src/main/res/values/strings.xml
Added values to the screen show inventory in the resource file
|:---|:---:|
|@ivans51|10|
Closes: https://github.com/flyve-mdm/android-inventory-agent/issues/103
Related #N/A
> WIP Translations for keys of the specs

- ci/scripts/github_release.sh
- ci/scripts/release.sh
- ci/scripts/setup_environment.sh
- package.json
Change environments
|:---|:---:|
|@ivans51|2|
Closes #N/A
Related #N/A
> Changes environments in Circle of Github

- ci/scripts/setup_environment.sh
Maintenance commands
`sudo apt-get update`
|:---|:---:|
|@ajsb85|1|
Closes #N/A
Related #N/A
> Maintenance commands

- .circleci/config.yml
- app/build.gradle
- build.gradle
- ci/scripts/generate_documentation.sh
- gradle/wrapper/gradle-wrapper.properties
- package.json
- yarn.lock
fix security alerts
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> fix(security): update deps (yarn and gem)

- yarn.lock
Fix yarn package alerts
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> update yarn package

- package.json
- yarn.lock
update standard-version to the latest version (7.0.0)
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Update standard-version to the latest version

- Gemfile.lock
Update gem bundle 1.17.3 to 2.0.2
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Update gem bundle 1.17.3 to 2.0.2

- app/src/main/java/org/flyve/inventory/agent/service/InventoryService.java
Fix compatibility intent with android 28
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Fix compatibility intent with android 28

- app/build.gradle
Bump inventory lib 0.12.0 to 1.3.6 =)
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Bump inventory lib 0.12.0 to 1.3.6

- .circleci/config.yml
- app/google-services.json
- ci/scripts/ci_licenses.sh
- ci/scripts/create_about_data.sh
- ci/scripts/google_cloud.sh
- ci/scripts/setup_environment.sh
- package.json
- yarn.lock
Fix CI script due to repo location change
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Update ci script

- fastlane/Fastfile
- fastlane/Screengrabfile
Fix fastlane step
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Fix fastlane step

- ci/scripts/deploy_alpha.sh
- fastlane/Appfile
- fastlane/Fastfile
Try yo fix fastlane step
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Fix ci fastlane

- app/build.gradle
- app/src/main/assets/about.properties
- ci/scripts/app_certification.sh
- ci/scripts/create_about_data.sh
- ci/scripts/setup_environment.sh
Fix CI / Build to bump version code
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Fix CI / Build to bump version code

- app/src/main/AndroidManifest.xml
- app/src/main/assets/about.properties
- app/src/main/java/org/glpi/inventory/agent/core/about/AboutModel.java
- package.json
Fix about informations
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Retrieve informations from properties

- app/src/main/assets/about.properties
- app/src/main/java/org/glpi/inventory/agent/utils/DataLoader.java
- app/src/main/java/org/glpi/inventory/agent/utils/Helpers.java
Fix bad user-agent on http headers when agent try to send inventory to GLPI
|:---|:---:|
|@|1|
Closes #N/A
Related #246
> Fix http user-agent informations

- app/build.gradle
- app/src/main/assets/about.properties
- ci/scripts/setup_environment.sh
Bump android inventory library from 1.3.6 to 1.4.0
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Bump android inventory library from 1.3.6 to 1.4.0

- fastlane/Fastfile
Since google API V3 status draft need to be set on fastlane supply 
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Add draft status to Fastlane CI

- app/src/main/assets/about.properties
- app/src/main/java/org/glpi/inventory/agent/ui/ActivityMain.java
- app/src/main/java/org/glpi/inventory/agent/utils/AgentLog.java
Improve log debug
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Improve log debug

- app/src/main/assets/about.properties
- app/src/main/java/org/glpi/inventory/agent/broadcast/TimeAlarm.java
- app/src/main/java/org/glpi/inventory/agent/core/splash/SplashModel.java
- app/src/main/java/org/glpi/inventory/agent/service/InventoryService.java
- app/src/main/java/org/glpi/inventory/agent/ui/DialogListServers.java
- app/src/main/res/xml/global_parameters.xml
Clean code not used
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Clean some code

- README.md
- app/src/main/assets/about.properties
update informations from README
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Update README informations

- ci/scripts/create_documentation.sh
- ci/scripts/google_cloud.sh
Fix build
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Prevent error on build

- README.md
- app/src/main/assets/about.properties
update informations from readme
remove f-droid link
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> update informations from readme

- app/src/androidTest/java/org/glpi/inventory/agent/InventoryTaskTest.java
- app/src/main/assets/about.properties
- app/src/main/java/org/glpi/inventory/agent/utils/UtilsAgent.java
- app/src/main/res/layout/activity_inventory.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_about.xml
- app/src/main/res/values/strings.xml
fix accessibility
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Fix accessibility

- app/src/main/assets/about.properties
- app/src/main/java/org/glpi/inventory/agent/ui/ActivityInventoryReport.java
Fix crash on orientation change
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Fix crash on orientation change

- app/src/main/java/org/glpi/inventory/agent/ui/FragmentHelp.java
- app/src/main/res/values/strings.xml
Prevent error from android lollipop and WebView
du to androidx compat package 
invite user to isntall webview app on playstore to solved this problem
it's SDK problem, not app problem
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Prevent error from android lollipop and WebView

- README.md
fix greenkeeper badge
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Fix greenkeeper badge

- app/build.gradle
- app/src/main/assets/about.properties
Update inventory library 1.4.3 to 1.4.4
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Update inventory library 1.4.3 to 1.4.4

- app/src/main/assets/about.properties
- app/src/main/java/org/glpi/inventory/agent/ui/ActivityDetailServer.java
Manage schedule inventory with deeplink and qrcode
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Manage schedule inventory with deeplink and qrcode

- README.md
- app/src/main/assets/about.properties
- app/src/main/java/org/glpi/inventory/agent/utils/DataLoader.java
Fix http request
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Fix http request

- app/src/main/assets/about.properties
- app/src/main/java/org/glpi/inventory/agent/core/report/ReportModel.java
- app/src/main/java/org/glpi/inventory/agent/ui/ActivityInventoryReport.java
Prevent error (transactiontoolarge) on share inventory
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Prevent error (transactiontoolarge) on share inventory

- app/src/main/assets/about.properties
- ci/scripts/github_release.sh
Do not add apk when release new version
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Do not add apk when release new version

- .circleci/config.yml
- ci/scripts/setup_environment.sh
fix build : java args, python
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> fix build : java args, python

- ci/scripts/setup_environment.sh
keep python2 for generate documentation add generate APK
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> keep python2

- ci/scripts/generate_documentation.sh
- ci/scripts/setup_environment.sh
fix circleci build
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> fix circle ci build

- ci/scripts/generate_documentation.sh
fix javadoc args
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> fix(doc): fix javadoc args

- package.json
- yarn.lock
security fix, upgrade package minimist and dot-prop
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> security fix, upgrade package minimist and dot-prop

- app/src/main/java/org/glpi/inventory/agent/utils/DataLoader.java
manage cyrillic content (tag softwares ...)
|:---|:---:|
|@|1|
Closes #N/A
Related #319
> Manage cyrillic content

- app/build.gradle
- app/src/main/assets/about.properties
- app/src/main/java/org/glpi/inventory/agent/ui/ActivityMain.java
- build.gradle
- ci/scripts/generate_documentation.sh
- ci/scripts/setup_environment.sh
- gradle/wrapper/gradle-wrapper.properties
fix build : java doc
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> fix(doc): fix generated doc

- app/build.gradle
- build.gradle
bump(gradle): update gradle to 4.0.2
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> bump(gradle): update gradle to 4.0.2

- .circleci/config.yml
disable create_doc from circleci
because of teclib_bot 
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> fix(build): disable create_doc from circleci

- fastlane/Fastfile
According to 
https://github.com/fastlane/fastlane/issues/18670
and
https://docs.fastlane.tools/actions/upload_to_play_store/
Need to define changes_not_sent_for_review to ```true```
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> fix(fastlane): set changes_not_sent_for_review arg

- app/src/main/res/xml/global_parameters.xml
fix default value
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> fix(core): fix default value

- yarn.lock
upgrade yarn packages
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> feat(dependencies): upgrade yarn packages

- app/src/main/java/org/glpi/inventory/agent/broadcast/BootStartAgent.java
- app/src/main/java/org/glpi/inventory/agent/service/InventoryService.java
fix(boot):fix boot for API < 26
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> fix(boot):fix boot for API < 26

- README.md
update readme
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> update(readme): update content

- README.md
- SUPPORT.md
readme review for professional support
> fix(readme): readme review for professional support

- .circleci/config.yml
- Gemfile.lock
- README.md
- SUPPORT.md
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/assets/about.properties
- app/src/main/java/org/glpi/inventory/agent/broadcast/BootStartAgent.java
- app/src/main/java/org/glpi/inventory/agent/broadcast/TimeAlarm.java
- app/src/main/java/org/glpi/inventory/agent/preference/GlobalParametersPreference.java
- app/src/main/java/org/glpi/inventory/agent/preference/InventoryParametersPreference.java
- app/src/main/java/org/glpi/inventory/agent/service/InventoryService.java
- app/src/main/java/org/glpi/inventory/agent/ui/ActivityDetailServer.java
- app/src/main/java/org/glpi/inventory/agent/ui/ActivityMain.java
- app/src/main/java/org/glpi/inventory/agent/ui/FragmentHelp.java
- app/src/main/java/org/glpi/inventory/agent/utils/DataLoader.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/global_parameters.xml
- build.gradle
- ci/scripts/generate_documentation.sh
- ci/scripts/setup_environment.sh
- fastlane/Fastfile
- gradle/wrapper/gradle-wrapper.properties
- package.json
- yarn.lock
New release
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> New release

- package.json
bump version
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> bump(core):  bump version

- ci/scripts/release.sh
Disable pre release process (not use yet)
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> build(release): disable github prerelease

- package.json
- yarn.lock
Upgrade packages
- trim-off-newlines
- semver-regex
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> build(yarn): upgrade packages

- README.md
fix version
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> fix(readme): fix GLPI Agent version

- app/src/main/AndroidManifest.xml
fix version value
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> fix(build): fix version value

- app/build.gradle
- app/src/main/assets/about.properties
- app/src/main/java/org/glpi/inventory/agent/core/detailserver/DetailServerModel.java
- app/src/main/java/org/glpi/inventory/agent/core/detailserver/DetailServerPresenter.java
- app/src/main/java/org/glpi/inventory/agent/schema/ServerSchema.java
- app/src/main/java/org/glpi/inventory/agent/service/InventoryService.java
- app/src/main/java/org/glpi/inventory/agent/ui/ActivityDetailServer.java
- app/src/main/java/org/glpi/inventory/agent/ui/DialogListServers.java
- app/src/main/java/org/glpi/inventory/agent/utils/HttpInventory.java
- app/src/main/java/org/glpi/inventory/agent/utils/Utils.java
- app/src/main/res/layout/activity_detail_server.xml
- app/src/main/res/values/strings.xml
GLPI Native inventory compatibility
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> feat(core): native inventory compatibility

- app/build.gradle
- app/src/main/assets/about.properties
bump Compil / Target SdkVersion to 30
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> feat(core): bump Compil / Target SdkVersion to 30

- app/src/main/java/org/glpi/inventory/agent/core/report/ReportModel.java
- app/src/main/java/org/glpi/inventory/agent/utils/Helpers.java
Fix path : now  ```data/data/org.glpi.invrentory.agent/files/```
Only share XML file
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Fix share inventory

- app/src/main/assets/about.properties
- package.json
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Merge from master

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/assets/about.properties
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Bump sdk version to 33
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> feat(core): bump SdkVersion to 33

- app/src/main/java/org/glpi/inventory/agent/ui/ActivityInventoryReport.java
- app/src/main/java/org/glpi/inventory/agent/ui/ActivityMain.java
- app/src/main/java/org/glpi/inventory/agent/ui/PermissionActivity.java
remove useless permissions about storage 
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> fix(permissions): remove useless permissions

- package.json
- yarn.lock
Bump package / deps
replace
https://github.com/glpi-project/android-inventory-agent/pull/388
https://github.com/glpi-project/android-inventory-agent/pull/385
https://github.com/glpi-project/android-inventory-agent/pull/384
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> build(deps): bump minimatch, decode-uri-component, semver-regex

- app/src/main/java/org/glpi/inventory/agent/broadcast/TimeAlarm.java
- app/src/main/java/org/glpi/inventory/agent/core/detailserver/DetailServerModel.java
- app/src/main/java/org/glpi/inventory/agent/schema/ServerSchema.java
- app/src/main/java/org/glpi/inventory/agent/service/InventoryService.java
- app/src/main/java/org/glpi/inventory/agent/ui/ActivityDetailServer.java
- app/src/main/java/org/glpi/inventory/agent/ui/DialogListServers.java
- app/src/main/java/org/glpi/inventory/agent/utils/HttpInventory.java
- app/src/main/res/layout/activity_detail_server.xml
- app/src/main/res/values/strings.xml
Add new option (server configuration) to allow overwriting of the serial number
Usefull when phone is WIP and serial number generated by agent changes
Simply reset the serial number in the server configuration. 
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> feat(Inventory): added option to override serial number

- .github/workflows/continuous-integration.yml
- .github/workflows/deploy-alpha.yml
- .github/workflows/deploy-prod.yml
- app/build.gradle
bump github action to prevent warning
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Fix(Build): bump github action

- package-lock.json
- package.json
- yarn.lock
bump dependencies
```shell
Package                       Current  Wanted  Latest  Location                                   Depended by
conventional-github-releaser   1.1.13  1.1.13   3.1.5  node_modules/conventional-github-releaser  android-inventory-agent
dot-prop                        4.2.1   4.2.1   9.0.0  node_modules/dot-prop                      android-inventory-agent
gh-pages                        5.0.0   5.0.0   6.1.1  node_modules/gh-pages                      android-inventory-agent
https-proxy-agent               2.2.4   2.2.4   7.0.5  node_modules/https-proxy-agent             android-inventory-agent
mem                             6.1.1   6.1.1   9.0.2  node_modules/mem                           android-inventory-agent
node-github-release             0.1.1   0.1.1 …
```
> Fix(Build): bump dependencies

- app/build.gradle
Feat(Build): move to SDK 34
|:---|:---:|
|@|1|
Closes #N/A
Related #N/A
> Feat(Build): move to SDK 34

- app/src/main/res/values/strings.xml
Same as https://github.com/glpi-project/android-inventory-agent/pull/409
Exclude sensitive strings (which should not be translated)
Fix : https://github.com/glpi-project/glpi-agent/discussions/805
> Fix(i18n): Exclude sensitive strings
